/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-02-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Vehicless {
    public Vehicless() {

    }

    //@AuraEnabled
   // public static List<Veicles__c> getVeicles(){
        //List<Veicles__c> lVeicles = new List<Veicles__c>(); //Lista para receber nossos veiculos
       // lVeicles = [SELECT id, Name, Year__c, Preview__c, Brand__c FROM Veicles__c];
        //system.debug('Lista de veiculos: ' + lVeicles);
       // return lVeicles;
    //}
}